services:
  chrony:
    extends:
      file: docker/chrony.yaml
      service: chrony
  coredns:
    extends:
      file: docker/coredns.yaml
      service: coredns
  etcd:
    extends:
      file: docker/etcd.yaml
      service: etcd
  isc-dhcp:
    extends:
      file: docker/isc-dhcp.yaml
      service: isc-dhcp
  cloudflared_ssh:
    extends:
      file: docker/cloudflared.yaml
      service: cloudflared_ssh
  haproxy:
    extends:
      file: docker/haproxy.yaml
      service: haproxy

volumes:
  etcd-data:
    driver: local
